import * as fs from 'fs';
import * as path from 'path';
import { generateRemoteProtocol, generateRemoteProtocolInvoking } from '@gaclib/codegen-remote-protocol';
import { GeneratedFile, generateWorkflowRpcFromFiles, writeWorkflowRpcGeneratedFiles } from '@gaclib/codegen-workflow-rpc';
import { generateSnapshotIndex, prepareSnapshots } from './snapshots.js';
import { quoteTypeScriptString } from './typeScript.js';

const __dirname = import.meta.dirname;

interface RpcTestIndexEntry {
    readonly name: string;
    readonly expected: string;
}

function readRpcTestIndex(indexPath: string): readonly RpcTestIndexEntry[] {
    if (!fs.existsSync(indexPath)) {
        throw new Error(`Workflow RPC conformance index is missing: ${indexPath}. Build Workflow's Test/UnitTest solution before running GacJS code generation.`);
    }
    const entries: RpcTestIndexEntry[] = [];
    const names = new Set<string>();
    const lines = fs.readFileSync(indexPath, 'utf8').split(/\r?\n/u);
    for (let index = 0; index < lines.length; index++) {
        const line = lines[index];
        if (line.length === 0) continue;
        const separator = line.indexOf('=');
        if (separator <= 0) {
            throw new Error(`Malformed Workflow RPC conformance entry at ${indexPath}:${String(index + 1)}. Expected <case>=<expected-result>.`);
        }
        const name = line.substring(0, separator);
        if (!/^[A-Za-z0-9_]+$/u.test(name)) {
            throw new Error(`Invalid Workflow RPC conformance case name at ${indexPath}:${String(index + 1)}: ${name}`);
        }
        if (names.has(name)) {
            throw new Error(`Duplicate Workflow RPC conformance case at ${indexPath}:${String(index + 1)}: ${name}`);
        }
        names.add(name);
        entries.push({ name, expected: line.substring(separator + 1) });
    }
    if (entries.length === 0) {
        throw new Error(`Workflow RPC conformance index contains no cases: ${indexPath}`);
    }
    return entries;
}

function emitRpcTestRegistry(entries: readonly RpcTestIndexEntry[]): GeneratedFile {
    const lines = [
        '// This file is generated by @gaclib-shared/codegen. Do not edit.',
        "import * as RPC from '@gaclib/workflow-rpc';",
        "import { rpcTestServiceFactories } from '../services/index.js';",
    ];
    for (const entry of entries) {
        lines.push(`import * as Case_${entry.name} from './cases/${entry.name}/generated.js';`);
    }
    lines.push(
        '',
        'export interface RpcTestContractModule {',
        '    readonly AllRpcInterfaceDescriptors: readonly RPC.RpcInterfaceDescriptor[];',
        '    configureRpcEndpoint(endpoint: RPC.RpcEndpoint): void;',
        '}',
        '',
        'export interface RpcTestServiceFactoryContext {',
        '    readonly endpoint: RPC.RpcEndpoint;',
        '    readonly contract: RpcTestContractModule;',
        '}',
        '',
        'export type RpcTestServiceFactory = (context: RpcTestServiceFactoryContext) => void;',
        '',
        'export interface RpcTestServiceFactories {',
    );
    for (const entry of entries) {
        lines.push(`    readonly '${entry.name}': RpcTestServiceFactory;`);
    }
    lines.push(
        '}',
        '',
        'export interface RpcTestCaseDefinition {',
        '    readonly name: string;',
        '    readonly expected: string;',
        '    readonly contract: RpcTestContractModule;',
        '    prepare(endpoint: RPC.RpcEndpoint): void;',
        '}',
        '',
        'function defineRpcTestCase(',
        '    name: keyof RpcTestServiceFactories,',
        '    expected: string,',
        '    contract: RpcTestContractModule,',
        '): RpcTestCaseDefinition {',
        '    return {',
        '        name,',
        '        expected,',
        '        contract,',
        '        prepare(endpoint): void {',
        '            contract.configureRpcEndpoint(endpoint);',
        '            rpcTestServiceFactories[name]({ endpoint, contract });',
        '        },',
        '    };',
        '}',
        '',
        'export const RpcTestCaseNames = [',
    );
    for (const entry of entries) {
        lines.push(`    '${entry.name}',`);
    }
    lines.push(
        '] as const;',
        '',
        'export type RpcTestCaseName = typeof RpcTestCaseNames[number];',
        '',
        'export const RpcTestCases: Readonly<Record<RpcTestCaseName, RpcTestCaseDefinition>> = {',
    );
    for (const entry of entries) {
        lines.push(`    '${entry.name}': defineRpcTestCase('${entry.name}', ${quoteTypeScriptString(entry.expected)}, Case_${entry.name}),`);
    }
    lines.push(
        '};',
        '',
        'export function selectRpcTestCase(name: string): RpcTestCaseDefinition {',
        '    const definition = (RpcTestCases as Readonly<Record<string, RpcTestCaseDefinition>>)[name];',
        '    if (definition === undefined) throw new Error(`Unknown Workflow RPC test case: ${name}`);',
        '    return definition;',
        '}',
    );
    return { path: 'registry.ts', content: `${lines.join('\n')}\n` };
}

function generateRpcTestCases(): void {
    const workflowRoot = path.resolve(__dirname, '../../../../../Workflow');
    const indexPath = path.join(workflowRoot, 'Test/Resources/IndexRpc.txt');
    const inputsRoot = path.join(workflowRoot, 'Test/Generated/RpcMetadata64');
    const outputRoot = path.resolve(__dirname, '../../../rpc-test/rpc-test-cases/src/generated');
    const entries = readRpcTestIndex(indexPath);
    for (const entry of entries) {
        generateWorkflowRpcFromFiles(
            path.join(inputsRoot, `Metadata_${entry.name}.txt`),
            path.join(inputsRoot, `Serialization_${entry.name}.d.ts`),
            path.join(outputRoot, 'cases', entry.name),
        );
    }
    writeWorkflowRpcGeneratedFiles(outputRoot, [emitRpcTestRegistry(entries)]);
}

const outputPath = path.resolve(__dirname, '../../../gaclib/remote-protocol/src');

generateRemoteProtocol(outputPath);
generateRemoteProtocolInvoking(outputPath);
const rpcMetadataPath = path.resolve(__dirname, '../../../../../GacUI/Test/GacUISrc/Generated_RemoteViewModelTest/Resource_x86/RpcMetadata.txt');
const rpcSchemaPath = path.resolve(__dirname, '../../../../../GacUI/Test/GacUISrc/Generated_RemoteViewModelTest/Resource_x86/RpcMetadata.d.ts');
const rpcOutputPath = path.resolve(__dirname, '../../../website/rvm/src/generated');
const rvmPackagePath = path.resolve(__dirname, '../../../website/rvm');
if (rpcOutputPath !== rvmPackagePath && !rpcOutputPath.startsWith(`${rvmPackagePath}${path.sep}`)) {
    throw new Error(`Workflow RPC output escapes website/rvm: ${rpcOutputPath}`);
}
generateWorkflowRpcFromFiles(rpcMetadataPath, rpcSchemaPath, rpcOutputPath);
generateRpcTestCases();
prepareSnapshots();
generateSnapshotIndex();
